{% set name = "odachi" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/odachi-{{ version }}.tar.gz
  sha256: 937f35e085ddb54f49fd38dde872d28b1e65de3b35d15d8c38396d63c6ff4038

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - tensorflow
    - rdkit

test:
  imports:
    - odachi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sudo-rushil/odachi
  summary: Advanced deep learning-based organic retrosynthesis engine
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
